FROM python:3.11-slim
WORKDIR /app
COPY cargo-ecommerce /app
RUN pip install --upgrade pip && pip install -r requirements.txt
CMD ["bash","-c","python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
EXPOSE 8000
